title: Abanoub | AI Engineer Portfolio
description: AI Systems Engineer & Data Scientist Portfolio
theme: jekyll-theme-hacker
baseurl: ""
url: "https://bonygeorge.github.io"
markdown: kramdown
github_username: BonyGeorge
linkedin_url: https://www.linkedin.com/in/abanoubgeorge/
email: you@example.com